version: '3'

services:
  sdxl-api:
    image: nhanvt2/sdxl-base-1.0:v0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./weights/sdxl-base:/network-volume/sd/sdxl-base
      - ./weights/flux_dev:/network-volume/sd/flux_dev
    environment:
      CHECKPOINT_PATH: "/network-volume/sd/sdxl-base"
      FLUX_DEV_CHECKPOINT: "/network-volume/sd/flux_dev/flux1-dev-fp8.safetensors"
      HF_TOKEN: "hf_token"
    ports:
      - 9500:8000
    command: bentoml serve bento_serving.py --host 0.0.0.0 --port 8000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
