version: '3'

services:
  sdxl-api:
    image: sdxl-base-1.0:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./weights/sdxl-base:/network-volume/sd/sdxl-base
    environment:
      CHECKPOINT_PATH: "/network-volume/sd/sdxl-base"
    ports:
      - 9500:8000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]
